### ISSUE TITLE
`cargo install hvm` considered harmful

### ISSUE THREAD

**Issue by tommythorn** [Kindelia/HVM#71]
ToT (61a331ffdc7c04567245f2cae969ab4643e91f20) doesn't appear to compile with gcc version 11.2.0 (from Ubuntu 21.10)

```
$ hvm c bench/Fibonacci/main.hvm
Compiled to 'bench/Fibonacci/main.c'.
$ gcc -O2 bench/Fibonacci/main.c
bench/Fibonacci/main.c:932:5: error: variably modified ‘normal_seen_data’ at file scope
  932 | u64 normal_seen_data[NORMAL_SEEN_MCAP];
      |     ^~~~~~~~~~~~~~~~
```

Digging in I see

```
#define NORMAL_SEEN_MCAP (HEAP_SIZE/sizeof(u64)/(sizeof(u64)*8))
const u64 HEAP_SIZE = 8 * U64_PER_GB * sizeof(u64);
```

**Comment by tommythorn** [comment]
Arrgh. The problem is that the README says to use `cargo install hvm` which doesn't install the current version.

Why does it say that instead of `cargo build --release`?

**Comment by VictorTaelin** [comment]
Wait, why it doesn't install the current version? I've published it. Can anyone with cargo experience let me know what is going on?

**Comment by nipzu** [comment]
By default, `cargo install hvm` downloads and compiles the latest version that is on [crates.io](https://crates.io/crates/hvm). The published version has been last updated 3 days ago (version 0.1.7), so it doesn't include 61a331f. In case @VictorTaelin has tried to publish a more recent version, a possible explanation I see is that the version number has not been bumped and crates.io ignores the changes because of that.

You can run `cargo install --path .` in a local repo or `cargo install --git https://github.com/Kindelia/HVM` if you want to install with the latest commits. `cargo build --release` compiles the local version, so it's what you want to use for development. [The Cargo Book](https://doc.rust-lang.org/cargo/) should have a lot of extra documentation for cargo commands.

**Comment by tommythorn** [comment]
I _just_ now ran `rustup update` and `cargo install --force hvm` and still got v0.1.7.  Reproduced the issue again:
```
hvm c bench/Fibonacci/main.hvm && gcc -Ofast bench/Fibonacci/main.c
Compiled to 'bench/Fibonacci/main.c'.
bench/Fibonacci/main.c:932:5: error: variably modified ‘normal_seen_data’ at file scope
  932 | u64 normal_seen_data[NORMAL_SEEN_MCAP];
      |     ^~~~~~~~~~~~~~~~
```

**Comment by tommythorn** [comment]
I still don't see the logic of using `cargo install` from crates.io when you already have the sources.  Maybe `cargo install --path .` as suggested above.

**Comment by quleuber** [comment]
Version `0.1.9` is [now published](https://crates.io/crates/hvm/versions) could you test?

@tommythorn

**Comment by tommythorn** [comment]
It's updated now, but I still find it this advice wrong - if you cloned the repo, you obviously expect to be working with the sources from the repo.

**Comment by nipzu** [comment]
You can run `cargo install hvm` without cloning the repo. It downloads the source automatically from crates.io to `$HOME/.cargo/registry/cache/` and builds from there.

**Comment by tommythorn** [comment]
Obviously, but how many people go to the repo and read the README without the intention of cloning it?  I posit that this is an unusual and confusing suggestion.

**Comment by quleuber** [comment]
Well, this instruction is not only shown on Github, but also on [crates.io](https://crates.io/crates/hvm) and wherever else replicates the README.

>how many people go to the repo and read the README without the intention of cloning it?

A lot, I guess. From my experience I would say most READMEs instruct to install from some package manager, the releases page, `cargo install <name>`, etc. ([example 1](https://github.com/BurntSushi/ripgrep#installation), [2](https://github.com/Rigellute/spotify-tui#cargo), [3](https://github.com/hrkfdn/ncspot#build)). I have no idea where you got that from.  :P

**Comment by PeterNjeim** [comment]
I think it's just a culture shock kind of moment for @tommythorn, because GitHub over the years has now been increasingly used by non-developers to get the programs they want, especially via the "Releases" page. For this reason, it is now common to have usage and installation instructions for non-developers at the top of the readme, with a separate section titled "building" or "contributing" for developers.

So I believe `cargo install x` is the correct thing to say in the readme. Consider a dedicated "Building" section for developers/tinkerers with relevant instructions there.

**Comment by nothingnesses** [comment]
Fwiw, the [Nix.md file](https://github.com/Kindelia/HVM/blob/master/NIX.md) file has instructions for building and installing using the Nix package manager which allows for reproducible builds, and exposes a development shell with dependencies included (such as clang) so you don't have to worry about installing and setting these up. It could be a more convenient alternative that's suitable for developers/tinkerers.

**Comment by quleuber** [comment]
Just published #79. What do you think?

**Comment by tommythorn** [comment]
Thanks.
